info/urls.py
from django.urls import path
from . import views

app_name = 'info'
urlpatterns = [
    path('promotion/', views.promotion, name='promotion'),
    path('contact/', views.contact, name='contact'),
    path('feedback/', views.feedback, name='feedback'),
    path('application/', views.application, name='application'),
    path('thankyou/<str:message>/', views.thankyou, name='thankyou'),
]

main/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

app_name = 'main'
urlpatterns = [
    # admin and landing
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing'),

    # all other apps
    path('tournaments/', include('tournament.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('entertainments/', include('entertainment.urls')),
    path('rinks/', include('rink.urls')),
    path('hotels/', include('hotel.urls')),
    path('reviews/', include('review.urls')),
    path('info/', include('info.urls')),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'
urlpatterns = [
    path('', views.restaurant_home, name='restaurant_home'),
    path('add_restaurant/', views.add_restaurant, name='add_restaurant'),
    path('<int:restaurant_id>/', views.get_restaurant, name='get_restaurant'),
    path('review_restaurant/<int:restaurant_id>/', views.review_restaurant, name='review_restaurant'),
]

restaurant/models.py
from django.db import models
from tournament.models import Location, Tournament
from main.choices import SERVING_TIME_CHOICES, RESTAURANT_PARKING_CHOICES, SEATING_TIME_CHOICES, PAYMENT_PROCESS_CHOICES, DRAFT_STATUS_CHOICES, FOOD_TYPE_CHOICES, PRICE_CHOICES
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg

class Restaurant(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    website = models.CharField(max_length=100, default='https://www.yhtreviews.com')
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    food_type = models.CharField(max_length=100, choices=FOOD_TYPE_CHOICES)
    gluten_free = models.BooleanField(default=False)
    vegan = models.BooleanField(default=False)
    dairy_free = models.BooleanField(default=False)
    vegetarian = models.BooleanField(default=False)
    meal_quality = models.FloatField(default=4.0, validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    service_quality = models.FloatField(default=4.0, validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    seating_time = models.CharField(max_length=25, choices=SEATING_TIME_CHOICES, default='30 minutes')
    serving_time = models.CharField(max_length=25, choices=SERVING_TIME_CHOICES, default='30 minutes')
    payment_process = models.CharField(max_length=20, choices=PAYMENT_PROCESS_CHOICES, default='Effortless')
    price = models.CharField(max_length=20, choices=PRICE_CHOICES, default='Reasonable')
    parking_size = models.CharField(max_length=10, choices=RESTAURANT_PARKING_CHOICES, default='medium')
    draft_status = models.CharField(max_length=10, choices=DRAFT_STATUS_CHOICES, default='draft')

    @property
    def overall_rating(self):
        return self.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0.0
    
    @property
    def total_upvotes(self):
        return self.reviews.filter(vote='upvote').count()

    @property
    def total_downvotes(self):
        return self.reviews.filter(vote='downvote').count()

    def __str__(self):
        return f"{self.name} ({self.food_type}) - {self.address}"

restaurant/forms.py
from django import forms
from .models import Restaurant

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'address', 'website', 'food_type', 'gluten_free', 'vegan', 'dairy_free', 'vegetarian', 'meal_quality', 'service_quality', 'seating_time', 'serving_time', 'payment_process', 'price', 'parking_size']
        labels = {
            'name': 'Restaurant Name',
            'address': 'Address',
            'website': 'Website',
            'food_type': 'Type of Cuisine',
            'gluten_free': 'Gluten-free Options Available',
            'vegan': 'Vegan Options Available',
            'dairy_free': 'Dairy-free Options Available',
            'vegetarian': 'Vegetarian Options Available',
            'meal_quality': 'Meal Quality',
            'service_quality': 'Service Quality',
            'seating_time': 'Average Seating Time',
            'serving_time': 'Average Serving Time',
            'payment_process': 'Payment Process',
            'price': 'Price Range',
            'parking_size': 'Parking',
        }
        help_texts = {
            'name': 'Enter the name of the restaurant.',
            'address': 'Enter the physical address of the restaurant.',
            'website': 'Enter the website of the restaurant.',
            'food_type': 'Select the type of cuisine offered by the restaurant.',
            'gluten_free': 'Check if the restaurant offers gluten-free options.',
            'vegan': 'Check if the restaurant offers vegan options.',
            'dairy_free': 'Check if the restaurant offers dairy-free options.',
            'vegetarian': 'Check if the restaurant offers vegetarian options.',
            'meal_quality': 'Rate the overall quality of meals provided by the restaurant (1-5).',
            'service_quality': 'Rate the overall quality of service provided by the restaurant (1-5).',
            'seating_time': 'Average time it takes for customers to be seated after arrival.',
            'serving_time': 'Average time it takes for meals to be served after ordering.',
            'payment_process': 'Describe the ease of the payment process at the restaurant.',
            'price': 'Select the price range of the restaurant.',
            'parking_size': 'Select the type of parking available at the restaurant.',
        }

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

def landing_page(request):
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    context = {
        'latitude': latitude,
        'longitude': longitude
    }
    return render(request, 'main/landing.html', context)
    

restaurant/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Restaurant
from tournament.models import Location
from django.db.models import Q
from main.regions import get_coordinates
from .forms import RestaurantForm
from main.choices import FOOD_TYPE_CHOICES
from review.models import RestaurantReview
from review.forms import RestaurantReviewForm

def restaurant_home(request):
    """
    Renders the home page for restaurants, allowing users to filter and view restaurant listings.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the restaurant home page.
    """
    # Retrieve filter parameters from the request
    selected_region = request.GET.get('region')
    user_latitude = request.GET.get('latitude')
    user_longitude = request.GET.get('longitude')
    selected_food_types = request.GET.getlist('food_type')

    # Prepare filter for restaurants
    restaurant_filter = Q()

    status_line = "Showing all restaurants."

    open_filters = False  # Default value for open_filters

    if user_latitude and user_longitude:
        # Define the maximum distance (in degrees) for nearby restaurants
        max_distance = .4  # Adjust as needed

        # Filter restaurants within the maximum distance from the user
        restaurant_filter &= Q(location__latitude__lte=float(user_latitude) + max_distance) & Q(location__latitude__gte=float(user_latitude) - max_distance) & Q(location__longitude__lte=float(user_longitude) + max_distance) & Q(location__longitude__gte=float(user_longitude) - max_distance)

        status_line += " Within 20-25 miles of your Location."

    # Filter restaurants by selected_region
    if selected_region and selected_region != 'All':
        restaurant_filter &= Q(location__region=selected_region)
        status_line += f" Filtered by region: {selected_region}."
        open_filters = True  # Set open_filters to True if selected region exists

    # Filter restaurants by selected food types
    if selected_food_types:
        restaurant_filter &= Q(food_type__in=selected_food_types)
        status_line += f" Filtered by food types: {', '.join(selected_food_types)}."
        open_filters = True  # Set open_filters to True if selected food types exist

    # Query restaurants using the built filter
    restaurant_listings = Restaurant.objects.filter(restaurant_filter, draft_status='published').order_by('name')

    context = {
        'restaurant_type_options': FOOD_TYPE_CHOICES,
        'selected_region': selected_region,
        'restaurant_listings': restaurant_listings,
        'selected_food_types': selected_food_types,
        'status_line': status_line,
        'open_filters': open_filters,  # Pass open_filters to the context   
    }
    return render(request, 'restaurant/restaurant_home.html', context)

def add_restaurant(request):
    """
    Renders the form to add a new restaurant and processes form submission.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the add restaurant page or redirecting to restaurant home.
    """
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            # Get the address entered by the user
            address = form.cleaned_data['address']

            # Call the get_coordinates function to get latitude and longitude
            coordinates = get_coordinates(address)

            # Create or update the Location model with the new coordinates
            location, created = Location.objects.get_or_create(region="All", defaults={'latitude': coordinates['lat'], 'longitude': coordinates['lng']})

            # Save the location object to ensure it's created or updated in the database
            location.save()

            restaurant = form.save(commit=False)
            restaurant.location = location  # Assign the location to the restaurant
            restaurant.draft_status = 'draft'
            restaurant.save()
            return redirect('review:thankyou', message='Your restaurant has been submitted. Give our team 1-2 days to review and publish it.')
    else:
        form = RestaurantForm()
    return render(request, 'restaurant/add_restaurant.html', {'form': form})

def get_restaurant(request, restaurant_id):
    """
    Renders the details of a specific restaurant.

    Args:
        request: HttpRequest object.
        restaurant_id: ID of the restaurant to retrieve.

    Returns:
        HttpResponse object rendering the restaurant details page.
    """
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    
    # Fetch reviews associated with the restaurant
    reviews = RestaurantReview.objects.filter(restaurant=restaurant)

    # Parse and apply filters from request parameters for REVIEWS
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    is_filtering = False

    # Filter reviews
    if start_date:
        reviews = reviews.filter(date__gte=start_date)
        is_filtering = True
    if end_date:
        reviews = reviews.filter(date__lte=end_date)
        is_filtering = True


    context = {
        'reviews': reviews,
        'restaurant': restaurant,
        'is_filtering': is_filtering,
        'start_date_value': start_date,
        'end_date_value': end_date,
    }
    return render(request, 'restaurant/details.html', context)

def review_restaurant(request, restaurant_id):
    """
    Renders the form for reviewing a specific restaurant and processes form submission.

    Args:
        request: HttpRequest object.
        restaurant_id: ID of the restaurant to review.

    Returns:
        HttpResponse object rendering the review restaurant page or redirecting to restaurant details page.
    """
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

    if request.method == 'POST':
        form = RestaurantReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.restaurant = restaurant
            review.save()
            return redirect('review:thankyou', message='Your review has been submitted.')
    else:
        initial_data = {'restaurant': restaurant}
        form = RestaurantReviewForm(initial=initial_data)

    return render(request, 'restaurant/review_restaurant.html', {'form': form, 'restaurant': restaurant})

main/templates/restaurant/add_restaurant.html
{% extends 'base.html' %}

{% block title %}Add Restaurant{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a restaurant listing.">  
    <link rel="stylesheet" href="{% static 'css/restaurant/add_restaurant.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">New Restaurant</h1>
        </div>
        <div class="form-wrapper">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button purple-theme" type="submit">Add Restaurant</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/restaurant/details.html
{% extends 'base.html' %}

{% block title %}Restaurant {{ restaurant.id }} {% endblock %}
{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for viewing the details of a selected restaurant.">  
    <link rel="stylesheet" href="{% static 'css/restaurant/details.css' %}">
    <script src="{% static 'js/restaurant/details.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <p class="text-black-50">{{ restaurant.food_type }}</p>
            <h1>{{ restaurant.name }}</h1>
            <p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{ restaurant.address }}">Directions</a></p>
        </div>
        <div class="col-md-6">
            <p><a target="_blank" href="{{ restaurant.website }}">Restaurant Website</a></p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                More Info
            </button>
        </div>
    </div>
    <div class="collapse show" id="collapseExample">
        <div class="row mt-3">
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Food Type:</span> <br>
                    {{ restaurant.food_type }}
                </p>
                <p class="text-small"><span class="fw-bold">Gluten Free:</span> <br>
                    {% if restaurant.gluten_free %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Vegan:</span> <br>
                    {% if restaurant.vegan %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Dairy Free:</span> <br>
                    {% if restaurant.dairy_free %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
            </div>
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Vegetarian:</span> <br>
                    {% if restaurant.vegetarian %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Meal Quality:</span> <br>
                    {{ restaurant.meal_quality }}
                </p>
                <p class="text-small"><span class="fw-bold">Service Quality:</span> <br>
                    {{ restaurant.service_quality }}
                </p>
                <p class="text-small"><span class="fw-bold">Seating Time:</span> <br>
                    {{ restaurant.seating_time }}
                </p>
            </div>
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Serving Time:</span> <br>
                    {{ restaurant.serving_time }}
                </p>
                <p class="text-small"><span class="fw-bold">Payment Process:</span> <br>
                    {{ restaurant.payment_process }}
                </p>
                <p class="text-small"><span class="fw-bold">Price:</span> <br>
                    {{ restaurant.price }}
                </p>
                <p class="text-small"><span class="fw-bold">Parking Size:</span> <br>
                    {{ restaurant.parking_size }}
                </p>
            </div>
            <div class="col-md-3">
                <!-- Add more attributes as needed -->
            </div>
        </div>
    </div>
</div>
<div class="container py-5">
    <hr>
    <div class="d-flex align-items-center justify-content-between">
        <h2>Reviews</h2>
        <div>
            <a href="{% url 'restaurant:review_restaurant' restaurant.id %}" class="btn btn-primary btn-sm ms-2"><i class="fas fa-plus"></i> Add Review</a>
        </div>
    </div>
    <div class="container pt-3">
        <p>
            <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
                Filters
            </button>
        </p>
        <div class="collapse {% if is_filtering %}show{% endif %}" id="filterCollapse">
            <form method="GET">
                <div class="row mb-3">
                    <div class="col">
                        <label for="start_date" class="form-label">Start Date:</label>
                        <input type="date" id="start_date" name="start_date" class="form-control" value="{{ start_date_value|default_if_none:'' }}">
                    </div>
                    <div class="col">
                        <label for="end_date" class="form-label">End Date:</label>
                        <input type="date" id="end_date" name="end_date" class="form-control" value="{{ end_date_value|default_if_none:'' }}">
                    </div>
                </div>

                <div class="col text-end">
                    <button type="submit" class="btn btn-primary">Filter</button>
                    <button type="button" class="btn btn-secondary" onclick="clearFilters()">Clear</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-2 g-4 py-3">
        {% for review in reviews %}
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ review.comment | truncatechars:120 }}</p>
                    <div class="text-end">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#reviewModal{{ review.id }}">Read more</a>
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ review.date }}</li>
                    <li class="list-group-item">Rating: {{ review.rating }}</li>
                </ul>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="reviewModal{{ review.id }}" tabindex="-1" aria-labelledby="reviewModalLabel{{ review.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="reviewModalLabel{{ review.id }}">Full Review</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p class="fw-bold">Experience</p>
                            <p>{{ review.comment }}</p>
                            <hr>
                            <p class="fw-bold">Parking</p>
                            {% if review.parking_notes %}
                                <p>{{ review.parking_notes }}</p>
                            {% else %}
                                <p class="text-muted">No parking notes for this review.</p>
                            {% endif %}
                            <hr>
                            <p class="fw-bold">Ratings</p>
                            <p>Vote: {{ review.vote }}</p>
                            <p>Referee: {{ review.referee_rating }}</p>
                            <p>Comms: {{ review.comms_rating }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">No reviews available for this range.</p>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/restaurant/get_restaurant.html
{% extends 'base.html' %}

{% block title %}Restaurant Details{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for viewing the details of a selected restaurant.">  
    <link rel="stylesheet" href="{% static 'css/restaurant/get_restaurant.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="section hero">
    <div class="container">
        <div class="hero-wrapper">
            <div class="restaurant-type-rating-wrapper">
                <div class="restaurant-type">{{ restaurant.food_type }}</div>
                <div class="restaurant-rating">Overall Rating [{{ restaurant.overall_rating }}]</div>
            </div>
            <h1 class="hero-title">{{ restaurant.name }}</h1>
            <div class="food-allergy-wrapper">
                <div class="allergy {% if restaurant.gluten_free %}gluten-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-wheat-awn"></i>
                </div>
                <div class="allergy {% if restaurant.vegan %}vegan-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-leaf"></i>
                </div>
                <div class="allergy {% if restaurant.dairy_free %}dairy-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-cow"></i>
                </div>
                <div class="allergy {% if restaurant.vegetarian %}vegetarian-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-carrot"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section links">
    <div class="container">
        <div class="restaurant-site"><i class="fa-solid fa-globe"></i> <a class="site-link" href="{{ restaurant.website }}" target="_blank">Offical Restaurant Site</a></div>
        <div class="restaurant-address"><i class="fa-regular fa-compass"></i> {{ restaurant.address }}</div>
    </div>
</div>

<div class="section details container">
    <div class="details-wrapper">
        <div class="section ratings">
            <div class="card rating-card">
                <h3 class="card-title">Ratings</h3>
                <div class="card-content">
                    <div class="content-label">Meal Quality</div>
                    <div class="content-value">{{ restaurant.meal_quality }} out of 5.0</div>
                </div>
                <div class="card-content">
                    <div class="content-label">Service Quality</div>
                    <div class="content-value">{{ restaurant.service_quality }} out of 5.0</div>
                </div>
            </div>
        </div>

        <div class="section agreement">
            <div class="card agreement-card">
                <h3 class="card-title">Payment</h3>
                <div class="card-content">
                    <div class="content-label">Payment Process</div>
                    <div class="content-value">{{ restaurant.payment_process }}</div>
                </div>
                <div class="card-content">
                    <div class="content-label">Price Range</div>
                    <div class="content-value">
                        {% if restaurant.price == 'Reasonable' %}
                            $
                        {% elif restaurant.price == 'Moderate' %}
                            $$
                        {% elif restaurant.price == 'Expensive' %}
                            $$$
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="section parking">
            <div class="card parking-card">
                <h3 class="card-title">Parking</h3>
                <div class="card-content-wrapper">
                    <div class="card-content parking">
                        <div class="content-label">Size</div>
                        <div class="content-value">{{ restaurant.parking_size }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section reviews">
    <hr>
    <div class="container">
        <h3 class="review-section-title">User Reviews</h3>
        <div class="split-wrapper">
            <div class="status-line">Showing all reviews</div>
            <div class="review-link"><a class="add-review-link" href="{% url 'restaurant:review_restaurant' restaurant.id %}">+ Add New Review</a></div>
        </div>
        <div class="reviews-wrapper">
            {% for review in reviews %}
            <div class="review">
                <div class="review-label">{{ review.date|date:"F" }}</div>
                <div class="review-preview">{{ review.comment }}</div>
            </div>
            {% empty %}
                <div class="review-status-line empty-review">Be the first to review this restaurant!</div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

main/templates/restaurant/restaurant_home.html
{% extends 'base.html' %}

{% block title %}Restaurant Listings{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Main restaurant listings page.">  
    <link rel="stylesheet" href="{% static 'css/restaurant/restaurant_home.css' %}">
    <script src="{% static 'js/restaurant/restaurant.js' %}"></script>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">Restaurant Listings</h1>
            
            <!-- Filter Component -->
            {% include 'components/restaurant_filter.html' %}
            
        </div>

        <!-- Results for: etc... -->
        <div class="split-wrapper">
            <div class="status-line">{{ status_line }}</div>
            <div class="listing-link"><a class="add-listing-link" href="{% url 'restaurant:add_restaurant' %}">+ Add New Listing</a></div>
        </div>
        

        <div class="results-wrapper">
            <div class="restaurant-list">
            {% for restaurant in restaurant_listings %}
                <div class="restaurant">
                    <div class="foodtype-with-buttons">
                        <div class="foodtype-label">
                            {{ restaurant.food_type }}
                        </div>
                        <div class="share-like-buttons">
                            <div><button onclick="shareLink('{{ restaurant.id }}')" class="button light-theme"><i class="fa-solid fa-arrow-up-from-bracket"></i> Share</button></div>
                            <div><button class="button red-theme disabled"><i class="fa-regular fa-heart"></i> Save</button></div>
                        </div>
                    </div>
                    <div class="restaurant-hero">
                        <div class="restaurant-rating">Rating [{{ restaurant.overall_rating }}]</div>
                        <div class="restaurant-name"><a class="restaurant-name-link" href="{% url 'restaurant:get_restaurant' restaurant.id %}">{{ restaurant.name }}</a></div>
                    </div>
                    <div class="restaurant-runner-details">
                        <div class="runner-detail">
                            <div class="detail-value">
                                {% if restaurant.price == 'Reasonable' %}
                                    $
                                {% elif restaurant.price == 'Moderate' %}
                                    $$
                                {% elif restaurant.price == 'Expensive' %}
                                    $$$
                                {% endif %}
                            </div>
                        </div>
                        <div class="spacer-dot">&#x2022;</div>
                        <div class="runner-detail">
                            <div class="detail-value">{{ restaurant.seating_time }} Seating</div>
                        </div>
                    </div>

                    <!-- Displays color if restaurant serves these types of options. -->
                    <div class="food-allergy-wrapper">
                        <div class="allergy {% if restaurant.gluten_free %}gluten-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-wheat-awn"></i>
                        </div>
                        <div class="allergy {% if restaurant.vegan %}vegan-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-leaf"></i>
                        </div>
                        <div class="allergy {% if restaurant.dairy_free %}dairy-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-cow"></i>
                        </div>
                        <div class="allergy {% if restaurant.vegetarian %}vegetarian-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-carrot"></i>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p class="section">No restaurants for the selected filters.</p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}