info/urls.py
from django.urls import path
from . import views

app_name = 'info'
urlpatterns = [
    path('promotion/', views.promotion, name='promotion'),
    path('contact/', views.contact, name='contact'),
    path('feedback/', views.feedback, name='feedback'),
    path('application/', views.application, name='application'),
    path('thankyou/<str:message>/', views.thankyou, name='thankyou'),
]

main/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

app_name = 'main'
urlpatterns = [
    # admin and landing
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing'),

    # all other apps
    path('tournaments/', include('tournament.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('entertainments/', include('entertainment.urls')),
    path('rinks/', include('rink.urls')),
    path('hotels/', include('hotel.urls')),
    path('reviews/', include('review.urls')),
    path('info/', include('info.urls')),
]

tournament/urls.py
from django.urls import path, include
from . import views

app_name = 'tournaments'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:tournament_id>/', views.get, name='get'),
    path('<int:tournament_id>/add_event/', views.add_event, name="add_event"),
    path('<int:tournament_id>/add_rink/', views.add_rink, name="add_rink"),
    path('<int:tournament_id>/add_hotel/', views.add_hotel, name="add_hotel"),
    path('<int:tournament_id>/add_restaurant/', views.add_restaurant, name="add_restaurant"),
    path('<int:tournament_id>/add_entertainment/', views.add_entertainment, name="add_entertainment"),
    path('<int:tournament_id>/<str:object_type>/success/', views.success, name='success'),
    path('<int:tournament_id>/review', views.review_tournament, name='review'),
]

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

def landing_page(request):
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    context = {
        'latitude': latitude,
        'longitude': longitude
    }
    return render(request, 'main/landing.html', context)
    

tournament/views.py
# This module handles views related to tournaments.
# Custom imports
from main.regions import get_coordinates

#  Util imports
import calendar
from django.db.models import Q
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

# Local imports
from .forms import TournamentForm, RinkForm, HotelForm, EventForm
from .models import Tournament, Location, Event
from rink.models import Rink
from hotel.models import Hotel

# Restaurant imports
from restaurant.forms import RestaurantForm
from restaurant.models import Restaurant

# Entertainment imports
from entertainment.forms import EntertainmentForm
from entertainment.models import Entertainment

# Reviews imports
from review.forms import TournamentReviewForm
from review.models import TournamentReview
from review.voting import update_vote_count


def index(request):
    """
    Renders the home page for tournaments, allowing users to view all tournament listings.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the tournament home page.
    """
    # Query all published tournaments
    tournament_listings = Tournament.objects.filter(draft_status='published').order_by('majorcity__name')

    # Parse and apply filters from request parameters
    major_city = request.GET.get('major_city')
    tournament_name = request.GET.get('tournament_name')
    is_filtering = False

    if major_city:
        tournament_listings = tournament_listings.filter(majorcity__name__icontains=major_city)
        is_filtering = True
    if tournament_name:
        tournament_listings = tournament_listings.filter(name__icontains=tournament_name)
        is_filtering = True

    # Pass filter values to context to prepopulate the form
    context = {
        'tournament_listings': tournament_listings,
        'is_filtering': is_filtering,
        'major_city_value': major_city,
        'tournament_name_value': tournament_name,
    }
    return render(request, 'tournament/index.html', context)

from django.urls import reverse

def create(request):
    """
    Renders the form to add a new tournament and processes form submission.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the add tournament page or redirecting to tournament home.
    """
    error_message = None
    tournament = None

    if request.method == 'POST':
        form = TournamentForm(request.POST)
        if form.is_valid():
            print("Form Data:", form.cleaned_data)
            # Check if a tournament with the same name already exists
            if Tournament.objects.filter(name__iexact=form.cleaned_data['name']).exists():
                error_message = "Tournament already exists."
            else:
                # Get the address entered by the user
                address = form.cleaned_data['address']
                coordinates = get_coordinates(address)
                location, created = Location.objects.get_or_create(region="All", defaults={'latitude': coordinates['lat'], 'longitude': coordinates['lng']})
                location.save()

                # Multiple Choice fields
                levels_of_play = form.cleaned_data['levels_of_play']
                age_groups = form.cleaned_data['age_groups']
                first_place_hardware = form.cleaned_data['first_place_hardware']
                second_place_hardware = form.cleaned_data['second_place_hardware']

                tournament = form.save(commit=False)
                tournament.location = location
                tournament.draft_status = 'published'
                tournament.save()

                # Post save, modify values
                tournament.levels_of_play.set(levels_of_play)
                tournament.age_groups.set(age_groups)
                tournament.first_place_hardware.set(first_place_hardware)
                tournament.second_place_hardware.set(second_place_hardware)

                # Redirect to the success page with tournament ID in the URL
                return redirect('tournaments:success', tournament_id=tournament.id, object_type='tournament')
    else:
        form = TournamentForm()

    context = {
        'form': form, 
        'tournament': tournament,
        'error_message': error_message
    }

    return render(request, 'tournament/create.html', context)


def get(request, tournament_id):
    # Retrieve the tournament object from the database based on the provided tournament_id
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    reviews = TournamentReview.objects.filter(tournament=tournament)

    # Fetch all rinks associated with the tournament
    rinks = Rink.objects.filter(tournament=tournament)
    
    # Fetch all restaurants associated with the tournament
    restaurants = Restaurant.objects.filter(tournament=tournament)

    # Fetch all the hotels associated with the tournament
    hotels = Hotel.objects.filter(tournament=tournament)

    # Fetch all entertainment associated with this tournament
    entertainments = Entertainment.objects.filter(tournament=tournament)

    # Fetch all events associated with this tournament
    events = Event.objects.filter(tournament=tournament)

    # Parse and apply filters from request parameters for REVIEWS
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    is_filtering = False

    # Filter reviews
    if start_date:
        reviews = reviews.filter(date__gte=start_date)
        is_filtering = True
    if end_date:
        reviews = reviews.filter(date__lte=end_date)
        is_filtering = True

    # Pass the tournament object and it's related reviews to the template
    context = {
        'tournament': tournament,
        'rinks': rinks,
        'events': events,
        'hotels': hotels,
        'restaurants': restaurants,
        'entertainments': entertainments,
        'reviews': reviews,
        'start_date_value': start_date,
        'end_date_value': end_date,
        'is_filtering': is_filtering,
    }

    # Render the template with the tournament details
    return render(request, 'tournament/details.html', context)

def review_tournament(request, tournament_id):
    """
    Renders the form for reviewing a specific tournament and processes form submission.

    Args:
        request: HttpRequest object.
        tournament_id: ID of the tournament to review.

    Returns:
        HttpResponse object rendering the review tournament page or redirecting to tournament details page.
    """
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    error_message = None

    if request.method == 'POST':
        form = TournamentReviewForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['author']
            # Check if a review with the same email already exists for the tournament
            if TournamentReview.objects.filter(tournament=tournament, author__iexact=email).exists():
                error_message = "You have already submitted a review for this tournament."
            else:
                review = form.save(commit=False)
                review.tournament = tournament
                review.save()
                return redirect('review:thankyou', message='Your review has been submitted.')
    else:
        initial_data = {'tournament': tournament}
        form = TournamentReviewForm(initial=initial_data)

    context = {
        'form': form, 
        'tournament': tournament,
        'error_message': error_message
    }
    return render(request, 'tournament/review_tournament.html', context)

def add_rink(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    error_message = None
    
    if request.method == 'POST':
        form = RinkForm(request.POST)
        if form.is_valid():
            if Rink.objects.filter(name__iexact=form.cleaned_data['name'], tournament=tournament).exists():
                error_message = "This rink already exists for the tournament."
            else:
                # Multiple choice fields
                parking_type = form.cleaned_data['parking_type']
                payment_modes = form.cleaned_data['payment_modes']
                offers_needs = form.cleaned_data['offers_needs']

                rink = form.save(commit=False)
                rink.tournament = tournament
                rink.save()

                # Set multiple choice fields
                rink.parking_type.set(parking_type)
                rink.payment_modes.set(payment_modes)
                rink.offers_needs.set(offers_needs)

                return redirect('tournaments:success', tournament_id=tournament_id, object_type='rink')
    else:
        form = RinkForm()
    
    context = {
        'form': form, 
        'tournament': tournament,
        'error_message': error_message
    }
    return render(request, 'tournament/add_rink.html', context)


def add_event(request, tournament_id):
    tournament = get_object_or_404(Tournament, pk=tournament_id)
    error_message = None

    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']

            # Check if an event with these dates already exists for this tournament
            if Event.objects.filter(tournament=tournament, start_date=start_date, end_date=end_date).exists():
                error_message = "Event already exists for this tournament."
            else:
                # Create a new event
                event = form.save(commit=False)
                event.tournament = tournament
                event.save()
                return redirect('tournaments:success', tournament_id=tournament_id, object_type='event')
    else:
        form = EventForm()

    context =  {

main/templates/tournament/add_entertainment.html
{% extends 'base.html' %}

{% block title %}Add Entertainment{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding tournament entertainment.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Hotel</h2>
    <p class="text-muted">For {{ tournament.name }}</p>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament events.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Event</h2>
    <p class="text-muted">For {{ tournament.name }}</p>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/add_hotel.html
{% extends 'base.html' %}

{% block title %}Add Hotel{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament hotel.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Hotel</h2>
    <p class="text-muted">For {{ tournament.name }}</p>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/add_restaurant.html
{% extends 'base.html' %}

{% block title %}Add Restaurant{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament restaurant.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Restaurant</h2>
    <p class="text-muted">For {{ tournament.name }}</p>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/add_rink.html
{% extends 'base.html' %}

{% block title %}Add Rink{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament rink.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Rink</h2>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/add_tournament.html
{% extends 'base.html' %}

{% block title %}Tournament Home{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament listing.">  
    <link rel="stylesheet" href="{% static 'css/tournament/add_tournament.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">New Tournament</h1>
        </div>
        <div class="form-wrapper">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button teal-theme" type="submit">Add Tournament</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/tournament/create.html
{% extends 'base.html' %}

{% block title %}Add Tournament{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a new tournament.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Add Tournament</h2>
    <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/index.html
{% extends 'base.html' %}

{% block title %}Tournament Home{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Main tournaments page.">  
    <script src="{% static 'js/tournament/index.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container pt-3">
    <p>
        <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
            Filters
        </button>
        <a class="btn btn-primary" href="{% url 'tournaments:create' %}">Submit New Tournament</a>
    </p>
    <div class="collapse {% if is_filtering %}show{% endif %}" id="filterCollapse">
        <form method="GET">
            <div class="row mb-3">
                <div class="col">
                    <label for="major_city" class="form-label">City Name:</label>
                    <input type="text" id="major_city" name="major_city" class="form-control" value="{{ major_city_value|default_if_none:'' }}">
                </div>
                <div class="col">
                    <label for="tournament_name" class="form-label">Tournament Name:</label>
                    <input type="text" id="tournament_name" name="tournament_name" class="form-control" value="{{ tournament_name_value|default_if_none:'' }}">
                </div>
            </div>
            <div class="col text-end">
                <button type="submit" class="btn btn-primary">Apply</button>
                <button type="button" class="btn btn-secondary" onclick="clearFilters()">Clear</button>
            </div>
        </form>
    </div>
</div>

<div class="container py-2">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for tournament in tournament_listings %}
        <div class="col">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-muted">{{ tournament.majorcity }}</li>
                </ul>
                <div class="card-body bg-dark text-light">
                    <h5 class="card-title"><a class="text-light" href="{% url 'tournaments:get' tournament.id %}">{{ tournament.name }}</a></h5>
                    <div class="d-flex align-items-center justify-content-between">
                        <p>{{ tournament.overall_rating }} / 5.0</p>
                        <p>{{ tournament.total_upvotes }} upvotes</p>
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Upcoming date:
                        {% if tournament.current_event %}
                            <p class="text-muted small">
                                {{ tournament.current_event.start_date }} - {{ tournament.current_event.end_date }}
                            </p>
                            <!-- Additional details of the current event can be displayed here -->
                        {% else %}
                            <p class="text-muted small">No Events yet.</p>
                        {% endif %}
                    </li>
                    <li class="list-group-item">
                        Levels of Play:
                        {% for age_category in tournament.levels_of_play.all %}
                            {{ age_category.name }}{% if not forloop.last %},{% endif %}
                        {% empty %}
                            <p class="text-muted small">Not Known Yet.</p>
                        {% endfor %}
                    </li>
                    <li class="list-group-item">
                        Age Groups:
                        {% for age_group in tournament.age_groups.all %}
                            {{ age_group.name }}{% if not forloop.last %},{% endif %}
                        {% empty %}
                            <p class="text-muted small">Not Known Yet.</p>
                        {% endfor %}
                    </li>
                    <li class="list-group-item">
                        Minimum Games Played:
                        {{ tournament.minimum_games_played }}
                    </li>
                    <li class="list-group-item">
                        Early Bird Discount:
                        {% if tournament.early_bird_discount %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </li>
                    <li class="list-group-item">
                        Multi-Team Discount:
                        {{ tournament.multi_team_discount }}
                    </li> 
                    <li class="list-group-item">
                        Other discounts:
                        {% if tournament.other_discounts %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/tournament/review_tournament.html
{% extends 'base.html' %}

{% block title %}Leave Review{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding a tournament review.">  
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="container mt-3 form-wrapper">
    {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
    {% endif %}
    <h2>Review Tournament</h2>
    <p class="text-muted">For {{ tournament.name }}</p>
    <form method="post" class="mt-3 form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

main/templates/tournament/success.html
{% extends 'base.html' %}

{% block title %}Success{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="A thank you and success page to display after the user has made a contributing to our site.">  
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="container">
        <div class="row mt-5">
            <div class="col-12 text-center">
                <h1 class="hero-title">Success!</h1>
                {% if messages %}
                    {% for message in messages %}
                        <p class="gray-text">{{ message }}</p>
                    {% endfor %}
                {% endif %}
                <br>
                <a class="btn btn-primary" href="{% url 'tournaments:get' tournament_id %}">Back to Tournament</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/tournament/tournament_home.html
{% extends 'base.html' %}

{% block title %}Tournament Home{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Main tournaments page.">  
    <link rel="stylesheet" href="{% static 'css/tournament/tournament_home.css' %}">
    <script src="{% static 'js/tournament/tournament.js' %}"></script>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">Tournament Listings</h1>
            
            <!-- Filter Component -->
            {% include 'components/tournament_filter.html' %}
            
        </div>

        <!-- Results for: etc... -->
        <div class="split-wrapper">
            <div class="status-line">{{ status_line }}</div>
            <div class="listing-link"><a class="add-listing-link" href="{% url 'tournaments:create' %}">+ Add New Listing</a></div>
        </div>
        

        <div class="results-wrapper">
            <div class="tournament-list">
            {% for tournament in tournament_listings %}
                <div class="tournament">
                    <div class="region-with-buttons">
                        <div class="region-label">
                            {{tournament.majorcity}}
                        </div>
                        <div class="share-like-buttons">
                            <div><button onclick="shareLink('{{ tournament.id }}')" class="button light-theme"><i class="fa-solid fa-arrow-up-from-bracket"></i> Share</button></div>
                            <div><button class="button red-theme disabled"><i class="fa-regular fa-heart"></i> Save</button></div>
                        </div>
                    </div>
                    <div class="tournament-hero">
                        <div class="tournament-rating">Rating [{{ tournament.overall_rating }}]</div>
                        <div class="tournament-name"><a class="tournament-name-link" href="{% url 'tournaments:get_tournament' tournament.id %}">{{ tournament.name }}</a></div>
                    </div>
                    <div class="tournament-runner-details">
                        <div class="runner-detail">{{tournament.date|date:"F"}}</div>
                        {% if tournament.stay_and_play %}
                            <div class="spacer-dot">&#x2022;</div>
                            <div class="runner-detail"> 
                                Stay & Play
                            </div>
                        {% else %}
                                
                        {% endif %}     
                        <div class="spacer-dot">&#x2022;</div>
                        <div class="runner-detail"> 
                            {{tournament.parking_cost}} Parking
                        </div>
                    </div>
                    <div class="tournament-content">
                    
                    </div>
                </div>
                {% empty %}
                <p class="section">No tournaments for the selected filters.</p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}