entertainment/urls.py
from django.urls import path
from . import views

app_name = 'entertainment'
urlpatterns = [
    path('', views.entertainment_home, name='entertainment_home'),
    path('add_entertainment/', views.add_entertainment, name='add_entertainment'),
    path('<int:entertainment_id>/', views.get_entertainment, name='get_entertainment'),
    path('review_entertainment/<int:entertainment_id>/', views.review_entertainment, name='review_entertainment'),
]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'
urlpatterns = [
    path('promotion/', views.promotion, name='promotion'),
    path('contact/', views.contact, name='contact'),
    path('feedback/', views.feedback, name='feedback'),
    path('application/', views.application, name='application'),
    path('thankyou/<str:message>/', views.thankyou, name='thankyou'),
]

main/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

app_name = 'main'
urlpatterns = [
    # admin and landing
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing'),

    # all other apps
    path('tournaments/', include('tournament.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('entertainments/', include('entertainment.urls')),
    path('rinks/', include('rink.urls')),
    path('hotels/', include('hotel.urls')),
    path('reviews/', include('review.urls')),
    path('info/', include('info.urls')),
]

entertainment/models.py
from django.db import models
from tournament.models import Location, Tournament
from main.choices import ACTIVITY_TYPE_CHOICES, AGE_RANGE_CHOICES, PARKING_SIZE_CHOICES, DRAFT_STATUS_CHOICES
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg

class Entertainment(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    website = models.CharField(max_length=100, default='https://www.yhtreviews.com')
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=100, choices=ACTIVITY_TYPE_CHOICES)
    description = models.TextField(blank=True, null=True)
    age_range = models.CharField(max_length=3, choices=AGE_RANGE_CHOICES)
    serve_beer = models.BooleanField(default=False)
    serve_wine = models.BooleanField(default=False)
    serve_liquor = models.BooleanField(default=False)
    take_cash = models.BooleanField(default=False)
    take_card = models.BooleanField(default=False)
    take_digital_payment = models.BooleanField(default=False)
    service_rating = models.FloatField(default=4.0, validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])
    parking_size = models.CharField(max_length=12, choices=PARKING_SIZE_CHOICES, default='medium')
    draft_status = models.CharField(max_length=10, choices=DRAFT_STATUS_CHOICES, default='draft')

    @property
    def overall_rating(self):
        return self.reviews.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0.0
    
    @property
    def total_upvotes(self):
        return self.reviews.filter(vote='upvote').count()

    @property
    def total_downvotes(self):
        return self.reviews.filter(vote='downvote').count()

    def __str__(self):
        return f"{self.name} - {self.address}"

entertainment/forms.py
from django import forms
from .models import Entertainment

class EntertainmentForm(forms.ModelForm):
    class Meta:
        model = Entertainment
        fields = ['name', 'address', 'website', 'activity_type', 'description','age_range', 
                  'serve_beer', 'serve_wine', 'serve_liquor', 'take_cash', 'take_card', 
                  'take_digital_payment', 'parking_size']
        labels = {
            'name': 'Name of Entertainment',
            'address': 'Address',
            'website': 'Website',
            'activity_type': 'Type of Activity',
            'description': 'Description',
            'age_range': 'Age Range',
            'serve_beer': 'Serve Beer?',
            'serve_wine': 'Serve Wine?',
            'serve_liquor': 'Serve Liquor?',
            'take_cash': 'Accept Cash?',
            'take_card': 'Accept Card?',
            'take_digital_payment': 'Accept Digital Payment?',
            'service_rating': 'Service Rating',
            'parking_size': 'Parking Size',
        }
        help_texts = {
            'name': 'Enter the name of the entertainment venue.',
            'address': 'Enter the address of the entertainment venue.',
            'website': 'Enter the website URL of the entertainment venue.',
            'activity_type': 'Select the type of activity offered by the entertainment venue.',
            'description': 'Describe the activity in a short summary.',
            'age_range': 'Select the minimum age range for which the entertainment venue is suitable.',
            'serve_beer': 'Check if the entertainment venue serves beer.',
            'serve_wine': 'Check if the entertainment venue serves wine.',
            'serve_liquor': 'Check if the entertainment venue serves liquor.',
            'take_cash': 'Check if the entertainment venue accepts cash payments.',
            'take_card': 'Check if the entertainment venue accepts card payments.',
            'take_digital_payment': 'Check if the entertainment venue accepts digital payments.',
            'service_rating': 'Rate the service of the entertainment venue on a scale of 1 to 5.',
            'parking_size': 'Select the size of parking available at the entertainment venue.',
        }

entertainment/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Entertainment
from django.db.models import Q
from main.choices import ACTIVITY_TYPE_CHOICES
from .forms import EntertainmentForm
from main.regions import get_coordinates
from tournament.models import Location
from review.models import EntertainmentReview
from review.forms import EntertainmentReviewForm

def entertainment_home(request):
    """
    Renders the home page for entertainment venues, allowing users to filter and view entertainment listings.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the entertainment home page.
    """
    # Retrieve filter parameters from the request
    selected_region = request.GET.get('region')
    user_latitude = request.GET.get('latitude')
    user_longitude = request.GET.get('longitude')
    selected_activity_types = request.GET.getlist('activity_type')

    # Prepare filter for entertainment venues
    entertainment_filter = Q()

    status_line = "Showing all entertainment venues."

    open_filters = False  # Default value for open_filters

    if user_latitude and user_longitude:
        # Define the maximum distance (in degrees) for nearby entertainment venues
        max_distance = 0.4  # Adjust as needed

        # Filter entertainment venues within the maximum distance from the user
        entertainment_filter &= Q(location__latitude__lte=float(user_latitude) + max_distance) & Q(location__latitude__gte=float(user_latitude) - max_distance) & Q(location__longitude__lte=float(user_longitude) + max_distance) & Q(location__longitude__gte=float(user_longitude) - max_distance)

        status_line += " Within 20-25 miles of your Location."

    # Filter entertainment venues by selected_region
    if selected_region and selected_region != 'All':
        entertainment_filter &= Q(location__region=selected_region)
        status_line += f" Filtered by region: {selected_region}."
        open_filters = True  # Set open_filters to True if selected region exists

    # Filter entertainment venues by selected activity types
    if selected_activity_types:
        entertainment_filter &= Q(activity_type__in=selected_activity_types)
        status_line += f" Filtered by activity types: {', '.join(selected_activity_types)}."
        open_filters = True  # Set open_filters to True if selected activity types exist

    # Query entertainment venues using the built filter
    entertainment_listings = Entertainment.objects.filter(entertainment_filter, draft_status='published').order_by('name')

    context = {
        'activity_type_choices': ACTIVITY_TYPE_CHOICES,
        'selected_region': selected_region,
        'entertainment_listings': entertainment_listings,
        'selected_activity_types': selected_activity_types,
        'status_line': status_line,
        'open_filters': open_filters,  # Pass open_filters to the context
    }
    return render(request, 'entertainment/entertainment_home.html', context)

def add_entertainment(request):
    """
    Renders the form to add a new entertainment and processes form submission.

    Args:
        request: HttpRequest object.

    Returns:
        HttpResponse object rendering the add entertainment page or redirecting to the entertainment home.
    """
    if request.method == 'POST':
        form = EntertainmentForm(request.POST)
        if form.is_valid():
            # Get the address entered by the user
            address = form.cleaned_data['address']

            # Call the get_coordinates function to get latitude and longitude
            coordinates = get_coordinates(address)

            # Create or update the Location model with the new coordinates
            location, created = Location.objects.get_or_create(region="All", defaults={'latitude': coordinates['lat'], 'longitude': coordinates['lng']})

            # Save the location object to ensure it's created or updated in the database
            location.save()

            entertainment = form.save(commit=False)
            entertainment.location = location  # Assign the location to the entertainment
            entertainment.draft_status = 'draft'
            entertainment.save()
            return redirect('review:thankyou', message='Your entertainment has been submitted. Give our team 1-2 days to review and publish it.')
    else:
        form = EntertainmentForm()
    return render(request, 'entertainment/add_entertainment.html', {'form': form})

def get_entertainment(request, entertainment_id):
    """
    Renders the details of a specific entertainment venue.

    Args:
        request: HttpRequest object.
        entertainment_id: ID of the entertainment venue to retrieve.

    Returns:
        HttpResponse object rendering the entertainment details page.
    """
    entertainment = get_object_or_404(Entertainment, pk=entertainment_id)
    
    # Fetch reviews associated with the entertainment venue
    reviews = EntertainmentReview.objects.filter(entertainment=entertainment)

    # Parse and apply filters from request parameters for REVIEWS
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    is_filtering = False

    # Filter reviews
    if start_date:
        reviews = reviews.filter(date__gte=start_date)
        is_filtering = True
    if end_date:
        reviews = reviews.filter(date__lte=end_date)
        is_filtering = True

    context = {
        'reviews': reviews,
        'entertainment': entertainment,
        'is_filtering': is_filtering,
        'start_date_value': start_date,
        'end_date_value': end_date,
    }
    return render(request, 'entertainment/details.html', context)

def review_entertainment(request, entertainment_id):
    """
    Renders the form for reviewing a specific entertainment and processes form submission.

    Args:
        request: HttpRequest object.
        entertainment_id: ID of the entertainment to review.

    Returns:
        HttpResponse object rendering the review entertainment page or redirecting to entertainment details page.
    """
    entertainment = get_object_or_404(Entertainment, pk=entertainment_id)

    if request.method == 'POST':
        form = EntertainmentReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.entertainment = entertainment
            review.save()
            return redirect('review:thankyou', message='Your review has been submitted.')
    else:
        initial_data = {'entertainment': entertainment}
        form = EntertainmentReviewForm(initial=initial_data)

    return render(request, 'entertainment/review_entertainment.html', {'form': form, 'entertainment': entertainment})

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

def landing_page(request):
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    context = {
        'latitude': latitude,
        'longitude': longitude
    }
    return render(request, 'main/landing.html', context)
    

main/templates/entertainment/add_entertainment.html
{% extends 'base.html' %}

{% block title %}Add Entertainment{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for adding an entertainment listing.">  
    <link rel="stylesheet" href="{% static 'css/entertainment/add_entertainment.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">New Entertainment</h1>
        </div>
        <div class="form-wrapper">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button green-theme" type="submit">Add Entertainment</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/entertainment/details.html
{% extends 'base.html' %}

{% block title %}Entertainment {{ entertainment.id }} {% endblock %}
{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for viewing the details of a selected entertainment.">  
    <link rel="stylesheet" href="{% static 'css/entertainment/details.css' %}">
    <script src="{% static 'js/entertainment/details.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <p class="text-black-50">{{ entertainment.activity_type }}</p>
            <h1>{{ entertainment.name }}</h1>
            <p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{ entertainment.address }}">Directions</a></p>
        </div>
        <div class="col-md-6">
            <p><a target="_blank" href="{{ entertainment.website }}">Entertainment Website</a></p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEntertainment" aria-expanded="false" aria-controls="collapseEntertainment">
                More Info
            </button>
        </div>
    </div>
    <div class="collapse show" id="collapseEntertainment">
        <div class="row mt-3">
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Age Range:</span> <br>
                    {{ entertainment.age_range }}
                </p>
                <p class="text-small"><span class="fw-bold">Serve Beer:</span> <br>
                    {% if entertainment.serve_beer %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Serve Wine:</span> <br>
                    {% if entertainment.serve_wine %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Serve Liquor:</span> <br>
                    {% if entertainment.serve_liquor %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
            </div>
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Take Cash:</span> <br>
                    {% if entertainment.take_cash %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Take Card:</span> <br>
                    {% if entertainment.take_card %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
                <p class="text-small"><span class="fw-bold">Take Digital Payment:</span> <br>
                    {% if entertainment.take_digital_payment %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </p>
            </div>
            <div class="col-md-3">
                <p class="text-small"><span class="fw-bold">Service Rating:</span> <br>
                    {{ entertainment.service_rating }}
                </p>
                <p class="text-small"><span class="fw-bold">Parking Size:</span> <br>
                    {{ entertainment.parking_size }}
                </p>
                <!-- Add more attributes as needed -->
            </div>
            <div class="col-md-3">
                
                <!-- Add more attributes as needed -->
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <p class="text-small"><span class="fw-bold">Description:</span> <br>
            {{ entertainment.description|default:"No description available" }}
        </p>
    </div>
</div>
<div class="container py-5">
    <hr>
    <div class="d-flex align-items-center justify-content-between">
        <h2>Reviews</h2>
        <div>
            <a href="{% url 'entertainment:review_entertainment' entertainment.id %}" class="btn btn-primary btn-sm ms-2"><i class="fas fa-plus"></i> Add Review</a>
        </div>
    </div>
    <div class="container pt-3">
        <p>
            <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
                Filters
            </button>
        </p>
        <div class="collapse {% if is_filtering %}show{% endif %}" id="filterCollapse">
            <form method="GET">
                <div class="row mb-3">
                    <div class="col">
                        <label for="start_date" class="form-label">Start Date:</label>
                        <input type="date" id="start_date" name="start_date" class="form-control" value="{{ start_date_value|default_if_none:'' }}">
                    </div>
                    <div class="col">
                        <label for="end_date" class="form-label">End Date:</label>
                        <input type="date" id="end_date" name="end_date" class="form-control" value="{{ end_date_value|default_if_none:'' }}">
                    </div>
                </div>

                <div class="col text-end">
                    <button type="submit" class="btn btn-primary">Filter</button>
                    <button type="button" class="btn btn-secondary" onclick="clearFilters()">Clear</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-2 g-4 py-3">
        {% for review in reviews %}
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ review.comment | truncatechars:120 }}</p>
                    <div class="text-end">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#reviewModal{{ review.id }}">Read more</a>
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ review.date }}</li>
                    <li class="list-group-item">Rating: {{ review.rating }}</li>
                </ul>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="reviewModal{{ review.id }}" tabindex="-1" aria-labelledby="reviewModalLabel{{ review.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="reviewModalLabel{{ review.id }}">Full Review</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p class="fw-bold">Experience</p>
                            <p>{{ review.comment }}</p>
                            <hr>
                            <p class="fw-bold">Parking</p>
                            {% if review.parking_notes %}
                                <p>{{ review.parking_notes }}</p>
                            {% else %}
                                <p class="text-muted">No parking notes for this review.</p>
                            {% endif %}
                            <hr>
                            <p class="fw-bold">Ratings</p>
                            <p>Vote: {{ review.vote }}</p>
                            <p>Referee: {{ review.referee_rating }}</p>
                            <p>Comms: {{ review.comms_rating }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">No reviews available for this range.</p>
                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/entertainment/entertainment_home.html
{% extends 'base.html' %}

{% block title %}Entertainment Listings{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Main entertainment listings page.">  
    <link rel="stylesheet" href="{% static 'css/entertainment/entertainment_home.css' %}">
    <script src="{% static 'js/entertainment/entertainment.js' %}"></script>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="hero-wrapper">
            <h1 class="hero-title">Entertainment Listings</h1>
            
            <!-- Filter Component -->
            {% include 'components/entertainment_filter.html' %}
            
        </div>

        <!-- Results for: etc... -->
        <div class="split-wrapper">
            <div class="status-line">{{ status_line }}</div>
            <div class="listing-link"><a class="add-listing-link" href="{% url 'entertainment:add_entertainment' %}">+ Add New Listing</a></div>
        </div>
        

        <div class="results-wrapper">
            <div class="entertainment-list">
            {% for entertainment in entertainment_listings %}
                <div class="entertainment">
                    <div class="activitytype-with-buttons">
                        <div class="activitytype-label">
                            {{ entertainment.activity_type }}
                        </div>
                        <div class="share-like-buttons">
                            <div><button onclick="shareLink('{{ entertainment.id }}')" class="button light-theme"><i class="fa-solid fa-arrow-up-from-bracket"></i> Share</button></div>
                            <div><button class="button red-theme disabled"><i class="fa-regular fa-heart"></i> Save</button></div>
                        </div>
                    </div>
                    <div class="entertainment-hero">
                        <div class="entertainment-rating">Rating [{{ entertainment.overall_rating }}]</div>
                        <div class="entertainment-name"><a class="entertainment-name-link" href="{% url 'entertainment:get_entertainment' entertainment.id %}">{{ entertainment.name }}</a></div>
                    </div>
                    <div class="entertainment-runner-details">
                        <div class="runner-detail">
                            <div class="detail-value">{{ entertainment.age_range }}</div>
                        </div>
                        <div class="spacer-dot">&#x2022;</div>
                        <div class="runner-detail">
                            <div class="detail-value">{{ entertainment.parking_size }}</div>
                        </div>
                    </div>

                    <!-- Displays icons if entertainment serves these types of options. -->
                    <div class="alcohol-wrapper">
                        <div class="alcohol {% if entertainment.serve_beer %}beer-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-beer-mug-empty"></i>
                        </div>
                        <div class="alcohol {% if entertainment.serve_wine %}wine-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-wine-glass"></i>
                        </div>
                        <div class="alcohol {% if entertainment.serve_liquor %}liquor-theme{% else %}gray-text{% endif %}">
                            <i class="fa-solid fa-martini-glass-citrus"></i>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p class="section">No entertainment venues for the selected filters.</p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/entertainment/get_entertainment.html
{% extends 'base.html' %}

{% block title %}Entertainment Details{% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Page for viewing the details of a selected entertainment venue.">  
    <link rel="stylesheet" href="{% static 'css/entertainment/get_entertainment.css' %}">
    <!-- <script src="{% static 'js/main/landing.js' %}"></script> -->
{% endblock %}

{% block content %}
<div class="section hero">
    <div class="container">
        <div class="hero-wrapper">
            <div class="activity-type-rating-wrapper">
                <div class="activity-type">{{ entertainment.activity_type }}</div>
                <div class="restaurant-rating">Overall Rating [{{ entertainment.overall_rating }}]</div>
            </div>
            
            <h1 class="hero-title">{{ entertainment.name }}</h1>
            <div class="alcohol-wrapper">
                <div class="alcohol {% if entertainment.serve_beer %}beer-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-beer-mug-empty"></i>
                </div>
                <div class="alcohol {% if entertainment.serve_wine %}wine-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-wine-glass"></i>
                </div>
                <div class="alcohol {% if entertainment.serve_liquor %}liquor-theme{% else %}gray-text{% endif %}">
                    <i class="fa-solid fa-martini-glass-citrus"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section links">
    <div class="container">
        <div class="entertainment-site"><i class="fa-solid fa-globe"></i> <a class="site-link" href="{{ entertainment.website }}" target="_blank">Official Entertainment Site</a></div>
        <div class="entertainment-address"><i class="fa-regular fa-compass"></i> {{ entertainment.address }}</div>
    </div>
</div>

<div class="section description">
    <div class="container">
        <h3 class="description-section-title">Description</h3>
        <div class="description-content">{{entertainment.description}}</div>
    </div>
</div>

<div class="section details container">
    <div class="details-wrapper">
        <div class="section rating">
            <div class="card agreement-card">
                <h3 class="card-title">Ratings</h3>
                <div class="card-content">
                    <div class="content-label">Service Quality</div>
                    <div class="content-value">{{ entertainment.service_rating }}</div>
                </div>
            </div>
        </div>
        <div class="section agreement">
            <div class="card agreement-card">
                <h3 class="card-title">Payment</h3>
                <div class="card-content">
                    <div class="content-label">Types</div>
                    <div class="content-value">
                    {% if entertainment.take_cash %}
                        <span class="payment-type">Cash, </span>
                    {% endif %}
                    {% if entertainment.take_card %}
                        <span class="payment-type">Card, </span>
                    {% endif %}
                    {% if entertainment.take_digital_payment %}
                        <span class="payment-type">Digital Payment</span>
                    {% endif %}
                    {% if not entertainment.take_cash and not entertainment.take_card and not entertainment.take_digital_payment %}
                        <span class="no-payment-type">No payment methods accepted</span>
                    {% endif %}
            </div>
                </div>
            </div>
        </div>

        <div class="section parking">
            <div class="card parking-card">
                <h3 class="card-title">Parking</h3>
                <div class="card-content-wrapper">
                    <div class="card-content parking">
                        <div class="content-label">Size</div>
                        <div class="content-value">{{ entertainment.parking_size }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section reviews">
    <hr>
    <div class="container">
        <h3 class="review-section-title">User Reviews</h3>
        <div class="split-wrapper">
            <div class="status-line">Showing all reviews</div>
            <div class="review-link"><a class="add-review-link" href="{% url 'entertainment:review_entertainment' entertainment.id %}">+ Add New Review</a></div>
        </div>
        <div class="reviews-wrapper">
            {% for review in reviews %}
            <div class="review">
                <div class="review-label">{{ review.date|date:"F" }}</div>
                <div class="review-preview">{{ review.comment }}</div>
            </div>
            {% empty %}
                <div class="review-status-line empty-review">Be the first to review this entertainment venue!</div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}