info/urls.py
from django.urls import path
from . import views

app_name = 'info'
urlpatterns = [
    path('promotion/', views.promotion, name='promotion'),
    path('contact/', views.contact, name='contact'),
    path('feedback/', views.feedback, name='feedback'),
    path('application/', views.application, name='application'),
    path('thankyou/<str:message>/', views.thankyou, name='thankyou'),
]

main/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

app_name = 'main'
urlpatterns = [
    # admin and landing
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing'),

    # all other apps
    path('tournaments/', include('tournament.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('entertainments/', include('entertainment.urls')),
    path('rinks/', include('rink.urls')),
    path('hotels/', include('hotel.urls')),
    path('reviews/', include('review.urls')),
    path('info/', include('info.urls')),
]

tournament/urls.py
from django.urls import path, include
from . import views

app_name = 'tournaments'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:tournament_id>/', views.get, name='get'),
    path('<int:tournament_id>/add_event/', views.add_event, name="add_event"),
    path('<int:tournament_id>/add_rink/', views.add_rink, name="add_rink"),
    path('<int:tournament_id>/add_hotel/', views.add_hotel, name="add_hotel"),
    path('<int:tournament_id>/add_restaurant/', views.add_restaurant, name="add_restaurant"),
    path('<int:tournament_id>/add_entertainment/', views.add_entertainment, name="add_entertainment"),
    path('<int:tournament_id>/<str:object_type>/success/', views.success, name='success'),
    path('<int:tournament_id>/review', views.review_tournament, name='review'),
]

main/views.py
from django.shortcuts import render
from django.http import JsonResponse

def landing_page(request):
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    context = {
        'latitude': latitude,
        'longitude': longitude
    }
    return render(request, 'main/landing.html', context)
    

main/templates/main/index.html
{% extends 'base.html' %}

{% block title %} Home page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Discover the hockey tournament review platform.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<section class="jumbotron" style="background-image: url('{% static 'images/background.jpg' %}')">
    <div class="container">
        <div class="title-actions-wrapper">
            <div class="title-container">
                <div class="title-wrapper">
                    <h1 class="title">Plan.</h1>
                    <h1 class="title">Connect.</h1>
                    <h1 id="review" class="title">Review.</h1>
                    <p class="subtitle">The ultimate hockey tournament review system.</p>
                </div>
            </div>
            <div class="action-container">
                <a class="action-link" href="{% url 'reviews:tournaments' %}"><i class="fa-solid fa-hockey-puck"></i> View Tournaments <i class="fa-solid fa-square-arrow-up-right"></i></a>
                <a class="action-link" href="{% url 'reviews:review' %}"><i class="fa-solid fa-hockey-puck"></i> Add Review <i class="fa-solid fa-square-arrow-up-right"></i></a>
                <a class="action-link" href="{% url 'reviews:faq' %}"><i class="fa-solid fa-hockey-puck"></i> Frequent Questions <i class="fa-regular fa-circle-question"></i></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/landing.html
{% extends 'base_home.html' %}

{% block title %} Home page {% endblock %}

{% load static %}

{% block extra_head %}
    <meta name="description" content="Discover the hockey tournament review platform.">  
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/main/landing.js' %}"></script>
    <script src="{% static 'js/main/location.js' %}"></script>
{% endblock %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading text-light">Plan. Connect. Review.</h1>
        <div class="row justify-content-center">
            <div class="col-md-6"> <!-- Use col-md-6 to take up 6 columns on medium-sized screens and center it -->
                <p class="lead text-light">Your go-to for youth hockey tournaments, nearby dining, entertainment, & hotels. Elevate your hockey experience today!</p>
            </div>
        </div>
        <p>
        <a href="{% url 'tournaments:index' %}" class="btn btn-primary my-2">View Tournaments</a>
        <a href="#" class="btn btn-secondary my-2">Learn More</a>
        </p>
    </div>
</section>
<div class="container px-4 py-5">
    <hr>
    <h2 class="pb-2">Our Features</h2>

    <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
      <div class="col d-flex flex-column align-items-start gap-2">
        <h2 class="text-body-emphasis">Hockey reviews. Community powered. You're the expert here.</h2>
        <p class="text-body-secondary">We give users the power to add new locations, leave reviews, and collaborate to shape this platform in the best way possible.</p>
        <a href="{% url 'tournaments:index' %}" class="btn btn-primary btn-lg">Get Started</a>
      </div>

      <div class="col">
        <div class="row row-cols-1 row-cols-sm-2 g-4">
          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-start fs-4 rounded-3">
              <img height="48px" class="rounded-3" src="{% static 'images/landing/rinks.jpg' %}" alt="" >
            </div>
            <h4 class="fw-semibold mb-0 text-body-emphasis">Rinks</h4>
            <p class="text-body-secondary">See all the rinks tournaments use before going.</p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-start fs-4 rounded-3">
                <img height="48px" class="rounded-3" src="{% static 'images/landing/restaurants.jpg' %}" alt="" >
            </div>
            <h4 class="fw-semibold mb-0 text-body-emphasis">Restaurants</h4>
            <p class="text-body-secondary">Find accommodating places to eat for your team.</p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-start fs-4 rounded-3">
              <img height="48px" class="rounded-3" src="{% static 'images/landing/entertainment.jpg' %}" alt="" >
            </div>
            <h4 class="fw-semibold mb-0 text-body-emphasis">Entertainment</h4>
            <p class="text-body-secondary">Plan out fun things to do while you're there.</p>
          </div>

          <div class="col d-flex flex-column gap-2">
            <div class="feature-icon-small d-inline-flex align-items-center justify-content-start fs-4 rounded-3">
              <img height="48px" class="rounded-3" src="{% static 'images/landing/hotels.jpg' %}" alt="" >
            </div>
            <h4 class="fw-semibold mb-0 text-body-emphasis">Hotels</h4>
            <p class="text-body-secondary">See the safest options for staying the night.</p>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}